### ISSUE TITLE
Problematic systematic_ids

### ISSUE THREAD

**Issue by manulera** [pombase/genome_changelog#22]
@ValWood @kimrutherford comes from https://github.com/pombase/curation/issues/3420

Here is a list of current systematic ids that have been used in different chromosomes before. Duplications are now gone.

```
systematic_id	chromosome
SPBC1348.01	I
SPBC1348.01	II
SPBC1348.02	I
SPBC1348.02	II
SPBC1348.03	I
SPBC1348.03	II
SPBC1348.04	I
SPBC1348.04	II
SPBC1348.05	I
SPBC1348.05	II
SPBC1348.06c	I
SPBC1348.06c	II
SPBC1348.07	I
SPBC1348.07	II
SPBC1348.08c	I
SPBC1348.08c	II
SPBC1348.09	I
SPBC1348.09	II
SPBC1348.10c	I
SPBC1348.10c	II
SPBC1348.11	I
SPBC1348.11	II
SPBC1348.12	I
SPBC1348.12	II
SPBC1348.13	I
SPBC1348.13	II
SPBC1348.14c	I
SPBC1348.14c	II
SPBPB21E7.01c	I
SPBPB21E7.01c	II
SPBPB21E7.02c	I
SPBPB21E7.02c	II
SPBPB21E7.04c	I
SPBPB21E7.04c	II
SPBPB21E7.05	I
SPBPB21E7.05	II
SPBPB21E7.06	I
SPBPB21E7.06	II
SPBPB21E7.07	I
SPBPB21E7.07	II
SPBPB21E7.08	I
SPBPB21E7.08	II
SPBPB21E7.09	I
SPBPB21E7.09	II
SPBPB21E7.10	I
SPBPB21E7.10	II
SPBPB8B6.02c	I
SPBPB8B6.02c	II
SPBPB8B6.03	I
SPBPB8B6.03	II
SPBPB8B6.04c	I
SPBPB8B6.04c	II
SPBPB8B6.05c	I
SPBPB8B6.05c	II
SPBPB8B6.06c	I
SPBPB8B6.06c	II
SPBTRNASER.06	II
SPBTRNASER.06	III
SPNCRNA.124	I
SPNCRNA.124	III
SPNCRNA.136	I
SPNCRNA.136	III
SPNCRNA.2001	I
SPNCRNA.2001	III
SPNCRNA.2002	I
SPNCRNA.2002	III
SPNCRNA.30	I
SPNCRNA.30	III
SPNCRNA.509	I
SPNCRNA.509	III
SPNCRNA.523	I
SPNCRNA.523	III
SPRRNA.01	III
SPRRNA.01	mitochondrial
```

**Comment by manulera** [comment]
Another problem I noticed by chance with `SPNCRNA.582`. This value is both a systematic id https://www.pombase.org/gene/SPNCRNA.582 and a synonym of a gene with a different systematic id https://www.pombase.org/gene/SPNCRNA.1208.

The problem exists for other values as well:

```tsv
synonym systematic_id
SPNCRNA.31      SPAPB1A11.06
SPNCRNA.543     SPBC13G1.16
SPNCRNA.521     SPCC70.06
SPNCRNA.582     SPNCRNA.1208
SPNCRNA.2001    SPNCRNA.1710
SPNCRNA.723     SPSNORNA.09,SPSNORNA.08,SPSNORNA.07
SPNCRNA.1394    SPSNORNA.35
SPNCRNA.901     SPSNORNA.43
SPNCRNA.1436    SPSNORNA.47
SPNCRNA.814     SPSNORNA.50
```

**Comment by manulera** [comment]
This one is a similar case:

```
revision        user    date    chromosome      systematic_id   primary_name    feature_type    added_or_removed
        value
7957    kmr44   2022-01-12      III     SPNCRNA.64              ncRNA   added   827254..827546
34      vw253   2011-08-29      III     SPNCRNA.64      prl64   misc_RNA        removed 827254..827546
20040915        -       2004-09-15      III     SPNCRNA.64      prl64   misc_RNA        added   827254..827546
```

The comment is `merged with SPCC1393.13`, but this was reverted as you can see above. How the genes look now (SPCC1393.13 is tuf89):

![Screenshot 2022-12-19 at 16 33 08](https://user-images.githubusercontent.com/22526102/208462124-462dbd42-427b-4ea6-b55d-4cbc07147199.png)

**Comment by ValWood** [comment]
SOme of these are the issue I talked about a few times. The data resubmitted for the Atkinson paper  provided RNAs which had previously been merged  and so we have 2 copies again. I am working through these right now (Just finished).

For 
 SPNCRNA.582  | SPNCRNA.1207 REMERGED

For the SNO ones, I  have not decided what to do with these.  Jurgs data predicts longer transcripts for most. I have kept them for now because there could be undiscovered snoRNAs in the longer transcripts, they are often encoded together and then processed, like this:
<img width="139" alt="Screenshot 2022-12-20 at 10 30 32" src="https://user-images.githubusercontent.com/7359272/208646061-c1422d02-8d40-4969-bc75-26795d8fc765.png">

**Comment by ValWood** [comment]
For the SNO ones, I  have not decided what to do with these.  Jurgs data predicts longer transcripts for most. I have kept them for now because there could be undiscovered snoRNAs in the longer transcripts, they are often encoded together and then processed, like this:
<img width="139" alt="Screenshot 2022-12-20 at 10 30 32" src="https://user-images.githubusercontent.com/7359272/208646061-c1422d02-8d40-4969-bc75-26795d8fc765.png">

**Comment by ValWood** [comment]
SPNCRNA.31      SPAPB1A11.06 This feature has oscillated between ncRNA and CDS. we have both features at the moment. I moved the ncRNA names on the dubious protein feature to be obsolete_name
SPNCRNA.543     SPBC13G1.16  SPNCRNA.543 was changed to a protein feature (Smp2 microprotein) but was re-imported with the  Atkinson data. I will obsolete the ncRNA feature.
SPNCRNA.521     SPCC70.06 removed synonym, I think we once decided this was likely the UTR of SPCC70.06 but this isn't clear
SPNCRNA.582     SPNCRNA.1208 RE- MERGED
SPNCRNA.2001    SPNCRNA.1710 I think  SPNCRNA.2001  is a synonym of SPNCRNA.1710 because we forgot we have assigned the ID range  SPNCRNA.2001 - to Jurg. I  can move to obsolete_name it as it wasn't used in the publication of SPNCRNA.1710,  I think it was only in PomBase for a short time

**Comment by ValWood** [comment]
Ah just saw this, I already commited the changes. 
I also have a list of the merges that I will send to you.
The ncRNA obsoletions are all in https://github.com/pombase/curation/issues/3410

**Comment by manulera** [comment]
Ok, I will probably manage anyway, I think most cases are covered so far. The question is really whether any of these problematic ids have annotations or whether they are in any gene list that was published before. We should probably show a list in PomBase listing these problematic ids.

**Comment by ValWood** [comment]
> We should probably show a list in PomBase listing these problematic ids.

We can just refer people to the change logs?
There should not be any data associated with them in PomBase. For, the merged features and data will just  go to the feature it was merged into (there is no coordinate specific data for the ncRNAs). But I'm pretty sure none of these  features  had any info associated with them yet.

**Comment by manulera** [comment]
Even in Jurg's non-coding RNA papers?

**Comment by ValWood** [comment]
There may be  phenotypes in the dataset of Maria's that you are processing, but this should easily map to the correct ID (with the exception of SPNCRNA.2001  assigned to SPNCRNA.1710, which was transient, and Jurg would have the correct ID here anyway).

Any data associated will still be correct if mapped to the extant feature based on the changes I have made.
It would be interesting to see if any of the phenotypes associated with the merged features are different though.

**Comment by ValWood** [comment]
tco1
https://github.com/pombase/curation/issues/3348
This is a weird one. I still need to deal with it. The longer transcript is a repressive transcript, it does not produce a CDS (even though it covers the coding region). We decided to represent these as non coding RNAs rather than  different protein isoforms (which is confusing and incorrect, as currently it seems as though there are 2 translations). I didn't get around to this yet.

**Comment by ValWood** [comment]
Done,

all info form the "alternative CDS" is now associated with the nc-transcript

/db_xref="PMID:29914874"
/systematic_id="SPNCRNA.600"
/product="translationally silent transcript from tco1 locus"
/primary_name="nc-tco1"
/controlled_curation="term=gene expression, RNA level; annotation_extension=during(GO:0071456); qualifier=increased; evidence=ECO:0005653; db_xref=PMID:18276645; date=20200924"
/controlled_curation="term=gene expression, RNA level; annotation_extension=in_presence_of(CHEBI:15379); qualifier=absent; evidence=ECO:0005653; db_xref=PMID:18276645; date=20200924"
/controlled_curation="term=misc, long tco1 transcript produced under low-oxygen conditions is not translated; db_xref=PMID:18276645; date=20200924"

**Comment by ValWood** [comment]
I should add that for the merges, I only merge if the info on both features could be merged, so any notes etc in Artemis, I review and carry over to the merged feature if they are correct.

**Comment by ValWood** [comment]
For the Ids which have sometimes been synonyms of protein features, I think this is OK, because I made them obsolete_name, and any future info will correctly go to the ncRNA. 
I think this  is fine for existing (and future data), because there is no coordinate-specific RNA data yet, like there is for proteins.

**Comment by ValWood** [comment]
SPNCRNA.64  was an 'end sequence' from an EST,  that later became clear was not a ncRNA but  part of the 3' UTR of SPCC1393.13 so it was 'merged' into this feature (well obsoleted actually) 
https://www.pombase.org/status/new-and-removed-genes
Then it was resubmitted with the Atkinson data. I will re-obsolete it. It isn't a ncRNA (although SPCC1393.13 may have alternative 3'UTRs).

**Comment by ValWood** [comment]
To discuss.
@kimrutherford  do any of the obsoleted ncRNAs have data associated with them, what happens to this if there is?

**Comment by kimrutherford** [comment]
> do any of the obsoleted ncRNAs

Do you mean this list in the first comment?: https://github.com/pombase/genome_changelog/issues/22#issue-1503090111
